name: Create Pull Request from Dev to Main

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: gh pr create -B main -H dev --title 'Merge dev into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
